# Generated by Django 5.1.3 on 2024-12-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='content',
            new_name='title',
        ),
    ]
